### ISSUE TITLE
Add Home Assistant custom component icon

### ISSUE THREAD

**Issue by carl-mayer** [ckarrie/homeassistant-oekofen#10]
It would be great to have an icon for this custom component on the Home Assistant UI. 
See https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

**Comment by ckarrie** [comment]
added PR https://github.com/home-assistant/brands/pull/4301

**Comment by ckarrie** [comment]
fixed in https://github.com/home-assistant/brands/commit/9085e53586fe5b747b97423971b6215222ba7f34
