### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by creadicted** [ckarrie/homeassistant-oekofen#2]
Thank you for the integration. I am missing, some values that are described in the const list. Looke like they are not implemented. WEIGHT_SENSORS_BY_DOMAIN for example.

**Comment by ckarrie** [comment]
Thanks for testing. Yeah I will add them soon (the weight Sensors were quite useless in my setup)

**Comment by creadicted** [comment]
Added a PR:
https://github.com/ckarrie/homeassistant-oekofen/pull/3

**Comment by ckarrie** [comment]
Merged, thanks for your code!
