### ISSUE TITLE
Typo in circ?

### ISSUE THREAD

**Issue by creadicted** [ckarrie/homeassistant-oekofen#4]
I don't have "circ" so I am not sure if this is a typo:

https://github.com/ckarrie/homeassistant-oekofen/blob/86429a0d12ec05254d6c30494c9bc55e8651706b/custom_components/ha_oekofen/const.py#L37

**Comment by ckarrie** [comment]
nope, I dont know why but in my Ökofen I get this, see 
[all.txt](https://github.com/ckarrie/homeassistant-oekofen/files/10673282/all.txt)

**Comment by ckarrie** [comment]
```json
 "circ1":{
  "circ_info":"circulation pump data",
  "L_pummp":{"val":1, "format":"0:Aus|1:Ein"}, 
  "L_ret_temp":{"val":546, "unit":"°C", "factor":0.1, "min":-32768, "max":32767}, 
  "L_release_temp":{"val":788, "unit":"°C", "factor":0.1, "min":-32768, "max":32767}, 
  "time_prg":{"val":0, "format":"0:Zeit 1|1:Zeit 2"}, 
  "mode":{"val":1, "format":"0:Aus|1:Auto"}, 
  "pump_release":{"val":300, "unit":"°C", "factor":0.1, "min":0, "max":900}, 
  "return_set":{"val":550, "unit":"°C", "factor":0.1, "min":0, "max":900}, 
  "name":{"val":"", "length":20}
 },
```

**Comment by ckarrie** [comment]
see https://github.com/ckarrie/oekofen-api/blob/main/oekofen_api/const.py#L51

**Comment by creadicted** [comment]
Then it's on their side XD
I just stumbled over it. Since I have no circ I could not validate.
