### ISSUE TITLE
Heat Once

### ISSUE THREAD

**Issue by stefnats** [ckarrie/homeassistant-oekofen#7]
Hey there,

first: Thanks for writing the integration, i've been looking for this for a long time.
In my Ökofen, i have the option to heat the water manually (it's called "Einmal aufheizen", i don't know the english phrase)

Would it be possible to offer such an action in home assistant?

**Comment by stefnats** [comment]
Update:
It seems to be:

[`ww{$n}.heat_once`](https://github.com/thannaske/oekofen-json-documentation#wwnheat_once)

**Comment by ckarrie** [comment]
Yes, good idea

**Comment by ckarrie** [comment]
[Switch platform](https://developers.home-assistant.io/docs/core/entity/switch) is a bad idea. [Button](https://developers.home-assistant.io/docs/core/entity/button) is better in my opinion.

i.e. the "DRÜCKEN" Buttons

![image](https://user-images.githubusercontent.com/4140156/219376670-468f92ad-4134-4580-813f-88713871380d.png)

**Comment by ckarrie** [comment]
Hi @stefnats could you check out the branch [switch](https://github.com/ckarrie/homeassistant-oekofen/tree/switch_entity) there you should be go

**Comment by ckarrie** [comment]
Hi @stefnats added the Buttons in https://github.com/ckarrie/homeassistant-oekofen/commit/97b1e4972cc4bbc76be003713575ef0eb2a8ec03 / v0.0.18

**Comment by ckarrie** [comment]
![image](https://user-images.githubusercontent.com/4140156/221376728-0fd23f5e-3ad4-423e-89d8-35cc147f176e.png)
